### PR TITLE
Mark VGrive as EOL

### PR DESCRIPTION
**Pull request by yakushabb**
> This application is no longer maintained.

Source: https://github.com/bcedu/VGrive

### CODE REVIEW

**Comment by ghost** [comment]
@bbhtt VGrive is no longer maintained.

I need to bypass the `non-png-icon-in-hicolor-size-folder` error to mark the application as EOL. Do you know how can I do this?

Thanks.

**Comment by bbhtt** [comment]
You have to rename them to `.png`, they are `.svg` currently.

**Comment by bbhtt** [comment]
That should fix the icons. Do you want to do the appdata patch?

**Comment by ghost** [comment]
> Do you want to do the appdata patch?

I will handle them. Thanks a lot.

**Pull request merged**
